### ISSUE TITLE
Namespace could be read from stencil.config

### ISSUE THREAD

**Issue by MonsieurMan** [natemoo-re/vscode-stencil-tools#2]
By default, the namespace for components could be read from **stencil.config.(ts | js)** 😄  

I'm not that much into vscode extensions but maybe you could read the config and hydrate settings when activating the extension in `doCheckWorkspace()` ?

**Comment by natemoo-re** [comment]
I love the idea, but I'm not sure if that's what the `namespace` config setting represents? If I'm interpreting [the docs](https://stenciljs.com/docs/config/#namespace) correctly, it seems like a human-readable string rather than the component prefix.

For example, `@ionic/core`'s [Stencil Config](https://github.com/ionic-team/ionic/blob/01323acd6a1ca0e49ea72cffa260ee15dc17cee5/core/stencil.config.js#L4) has `namespace: "Ionic"`, but all of their components are prefixed with `ion-`.

Something like that could be accomplished now by manually adding the following to `.vscode/settings.json`.

```json
{
     "stencilTools.component.prefix": "ion"
}
```

Any thoughts?


_PS: v3 will be aware of the `stencil.config.{js|ts}` file, for things like automatically generating the correct style file type (css|scss|styl|etc) based on the plugins section._

**Comment by MonsieurMan** [comment]
Oh yes, you're right, it's not the same thing. I just checked and it seems to be used only for namespacing the produced bundles, which happened to be the same as the component prefix in my case.  
I guess there's not much more we can do about it then !  

PS: That's a good thing you mentioned it, I almost created another issue haha !
